version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.12.12-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:8.11.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  services.accounts:
    image: services.accounts
    environment:
      - ConnectionStrings__PostgreSQL=Host=postgres:5432;Database=db_reservations;Username=user;Password=password
      - ConnectionStrings__RabbitMQ=amqp://user:password@rabbitmq:5672
    ports:
      - "5400:5400"
    depends_on:
      - rabbitmq
      - postgres
    restart: on-failure

  services.doctors:
    image: services.doctors
    environment:
      - ConnectionStrings__Elasticsearch=http://elasticsearch:9200
      - ConnectionStrings__RabbitMQ=amqp://user:password@rabbitmq:5672
    ports:
      - "5410:5410"
    depends_on:
      - rabbitmq
      - elasticsearch
    restart: on-failure

  services.reservations:
    image: services.reservations
    environment:
      - ConnectionStrings__PostgreSQL=Host=postgres:5432;Database=db_reservations;Username=user;Password=password
      - ConnectionStrings__RabbitMQ=amqp://user:password@rabbitmq:5672
    ports:
      - "5420:5420"
    depends_on:
      - rabbitmq
      - postgres
    restart: on-failure

  webapi.rest:
    image: webapi.rest
    environment:
      - ConnectionStrings__Services.Accounts=http://services.accounts:5400
      - ConnectionStrings__Services.Doctors=http://services.doctors:5410
      - ConnectionStrings__Services.Reservations=http://services.reservations:5420
    ports:
      - "80:8080"
    depends_on:
      - services.accounts
      - services.doctors
      - services.reservations
